### ISSUE TITLE
COE2. "Find Intel"-task problem

### ISSUE THREAD

**Issue by Mimi-Sa** [Kexanone/COE2_AR#4]
Occasionally intel-folder can not be found (not existing/disappeared). It would be convenient to have some kind of failsafe, which would allow cancelling the task and subsequently activate the exfil. Especially, this would be nice if AO contained two or three tasks and finding the intel, being one of them, fails and disables the generation of exfil.

**Comment by Mimi-Sa** [comment]
Cannot remember the village (was marked within a buiding, we checked the location and actually the whole village as well). The intel-mission was visible in the map, but we were not able to find it in-game. I also looked for it in GM, but without success. This was the second tadk within AO and we tried to cancel this intel-task in order to spawn exfil-task. Can one do this kind of cancelling within the mission?

**Comment by Kexanone** [comment]
I suspect it could have been the garbage collector at this point. On the other hand, the intel can be well hidden sometimes. Again, you can check it in GM, since there's a white dot at the intel's location:

![image](https://github.com/Kexanone/COE2_AR/assets/18646707/9e12dc9f-5b2e-4934-8901-36495648d917)

> Can one do this kind of cancelling within the mission?

Yes, you can do the cancelling from anywhere. All board commands are also available in the commanding menu (`~` by default on PC).

**Comment by Kexanone** [comment]
Fixed in Kexanone/ArmaReforgerMods@c008132de024cfb701c8295e709b801c92919de6
